### ISSUE TITLE
Commands like ENTER, SPACE, or q have no effect

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/lessport#2]
`./less file.txt`

Where file.txt is an existing file.

Pressing ENTER, SPACE or q has no effect

**Comment by IgorTodorovskiIBM** [comment]
FYI @AnthonyGiorgio

**Comment by ZOSOpenTools** [comment]
Have a fix here: https://github.com/ZOSOpenTools/lessport/pull/3

**Comment by covener** [comment]
For others who stumble across this: It seems like the fix is only effective if you pull in the .env for ncurses too.

**Comment by AnthonyGiorgio** [comment]
@IgorTodorovskiIBM This seems to be working in the latest `less` releases.  I'm closing the issue.
